apiVersion: v1
kind: Service
metadata:
  name: homarr-service
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: homarr
  ports:
    - port: 7575
      protocol: TCP
      targetPort: 7575

