apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-data
  namespace: media
  labels:
    app: homarr
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 3G
  storageClassName: local-path
  