apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config
  namespace: media
  labels:
    app: homarr
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 350Mi
  storageClassName: local-path
  