apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sons-of-the-forest-wine-pvc
  namespace: sons-of-the-forest
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi