apiVersion: v1
kind: Service
metadata:
  name: sons-of-the-forest
  namespace: games
spec:
  type: NodePort
  selector:
    app: sons-of-the-forest
  ports:
    - port: 8766
      name: sons-of-the-forest-port-1
      nodePort: 32456
      protocol: UDP
    - port: 27016
      name: sons-of-the-forest-port-2
      nodePort: 32457
      protocol: UDP
    - port: 9700
      name: sons-of-the-forest-port-3
      nodePort: 32458
      protocol: UDP