apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sons-of-the-forest-config-pvc
  namespace: games
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi