---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-secrets-store
  namespace: flux-system
spec:
  interval: 2h
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts