apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepass
  namespace: flux-system
spec:
  # type: oci
  interval: 5m
  url: https://1password.github.io/connect-helm-charts
