apiVersion: v1
kind: Service
metadata:
  name: biggs-service
  namespace: gregbob
spec:
  type: ClusterIP
  selector:
    app: biggs
  ports:
    - name: biggs-port
      port: 8080
      protocol: TCP
