apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-config
  namespace: joplin
  labels:
    app: joplin
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: local-path
  