apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joplin
  name: joplin
  namespace: joplin
spec:
  template:
    metadata:
      labels:
        app: joplin
    spec:
      containers:
        - image: joplin/server:latest
          imagePullPolicy: Always
          name: joplin
          env:
          - name: DB_CLIENT
            value: "pg"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: joplin-superuser-password
                key: password
          - name: POSTGRES_DATABASE
            value: "joplin"
          - name: POSTGRES_USER
            value: "joplin"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_HOST
            value: "cnpg-joplin-rw.cnpg-system.svc.cluster.local"
          - name: APP_BASE_URL
            value: "https://joplin.biggs.dog"
          ports:
          - name: joplin
            containerPort: 22300
            protocol: TCP
          volumeMounts:
          - name: joplin-config
            mountPath: /config
          resources:
            requests:
              memory: 275Mi
              cpu: 75m
            limits:
              memory: 450Mi
              cpu: 300m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: joplin-config
        persistentVolumeClaim:
          claimName: "joplin-config"
  selector:
    matchLabels:
      app: joplin