apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      #version: 0.0.0
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1m