apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: grafana-admin-credentials
    namespace: observability
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        creationPolicy: Owner
    data:
        - secretKey: password
          remoteRef:
            key: grafana-admin-credentials
            property: password
        - secretKey: username
          remoteRef:
            key: grafana-admin-credentials
            property: username

