apiVersion: v1
kind: Service
metadata:
  name: readarr-service
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: readarr
  ports:
    - port: 8787
      protocol: TCP
      targetPort: 8787
