apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: media
  labels:
    app: readarr
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
  