apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-biggs-dog
  namespace: kube-system
spec:
  secretName: cloudflare-tls
  dnsNames:
  - "*.biggs.dog"
  - biggs.dog
  # commonName: "*.biggs.dog"
  issuerRef:
    name: letsencrypt-staging    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer