---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./victoria-logs/ks.yaml
  - ./victoria-metrics/ks.yaml
  - ./grafana-operator/ks.yaml

  