apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: renovate-user-password
    namespace: renovate
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        creationPolicy: Owner
    data:
        - secretKey: password
          remoteRef:
            key: renovate-user-password
            property: password
        - secretKey: username
          remoteRef:
            key: renovate-user-password
            property: username

