apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-config
  namespace: renovate
  labels:
    app: renovate
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: local-path
  