apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: renovate-github-secret
    namespace: renovate
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        creationPolicy: Owner
    data:
        - secretKey: app-id
          remoteRef:
            key: renovate-github-secret
            property: app-id
        - secretKey: credential
          remoteRef:
            key: renovate-github-secret
            property: credential


