apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-data-pvc
  namespace: games
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi