apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-backup-pvc
  namespace: valheim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi