apiVersion: v1
kind: PersistentVolume
metadata:
  name: books-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
    - hard
    - noatime
    - nconnect=16
    - nfsvers=4.2
  nfs:
    path: /tank/media/books
    server: 192.168.2.30