apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cwa
  name: cwa
  namespace: media
spec:
  template:
    metadata:
      labels:
        app: cwa
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-03
      containers:
        - image: crocodilestick/calibre-web-automated:dev
          imagePullPolicy: Always
          name: cwa
          env:
          - name: TZ
            value: "Europe/Helsinki"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          # - name: NETWORK_SHARE_MODE
          #   value: "true"
          - name: CWA_PORT_OVERRIDE
            value: "8083"
          ports:
          - name: cwa-port
            containerPort: 8083
            protocol: TCP
          volumeMounts:
          - name: cwa-config
            mountPath: /cwa/config
          - name: cwa-library
            mountPath: /cwa/library
          - name: cwa-ingest-cache
            mountPath: /cwa-book-ingest
          - name: cwa-plugins
            mountPath: /config/.config/calibre/plugins
          - name: books-pvc
            mountPath: /books
          resources:
            requests:
              memory: 350Mi
              cpu: 75m
            limits:
              memory: 500Mi
              cpu: 500m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: cwa-config
        persistentVolumeClaim:
          claimName: "cwa-config"
      - name: cwa-library
        persistentVolumeClaim:
          claimName: "cwa-library"
      - name: cwa-ingest-cache
        persistentVolumeClaim:
          claimName: "cwa-ingest-cache"
      - name: cwa-plugins
        persistentVolumeClaim:
          claimName: "cwa-plugins"
      - name: books-pvc
        persistentVolumeClaim:
          claimName: books-pvc
  selector:
    matchLabels:
      app: cwa