apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cwa-library
  namespace: media
  labels:
    app: cwa
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
  