apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cwa-ingest-cache-pvc
  namespace: media
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi