apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cwa-ingest-cache
  namespace: media
  labels:
    app: cwa
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
  