apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-services
  namespace: media
  labels:
    app: lidarr
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: local-path
  