apiVersion: v1
kind: Service
metadata:
  name: lidarr-service
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: lidarr
  ports:
    - port: 8686
      protocol: TCP
      targetPort: 8686

