apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-user-password
  namespace: cnpg-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: "grafana-user-password"
      property: password
  - secretKey: username
    remoteRef:
      key: "grafana-user-password"
      property: username
