apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: joplin-user-password
    namespace: cnpg-system
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        creationPolicy: Owner
    data:
        - secretKey: password
          remoteRef:
            key: joplin-user-password
            property: password
        - secretKey: username
          remoteRef:
            key: joplin-user-password
            property: username

