apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: joplin-superuser-password
    namespace: joplin
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
        creationPolicy: Owner
    data:
        - secretKey: password
          remoteRef:
            key: joplin-superuser-password
            property: password
