apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
  labels:
    app: jellyfin
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 100G
  storageClassName: local-path
  