apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudflare-api-token
  target:
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: "cloudflare-api-token"
      property: api-token

