apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
data:
    api-token: ENC[AES256_GCM,data:GCBoaSPkYb2PqEY2HPyq9ZOUi47CW6Ynkac8AEqnAv4KQ1cZeH4h/g==,iv:hUg4zGsjEjFJSqG4cRi+O8jyai3dxPkW1h5ho4HdvkM=,tag:HpsO0kQlgYLc0KjJQKPj8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age190ldxpeqm783nz8rf3cxeajq2m0rflan4huhau8fz9tqcj96wgvsmycw9d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaXBCTGVSVzhBSVlEeVlu
            UFcxUUM1SG9laGRHQm1Ocy9nT0k1dG9VdlZZCjgycDMvdzJ2Q21UMCs5TDZWbzhG
            SmRMcTVZbUozanJVd2N0QnhtWk5scFEKLS0tIE1kVlRGTUMwemxZZU5SdTR0TEoz
            eHgweDNTZjBDY3Y1S0paSk5ONTlZSkkKBj1X/u8pVCN7xs11v0QdXxXqVIrxcmud
            vCGJPmE5u+nq/wnttPupfb7W/C59jKqlc889xJR+UtNqd7bJsnysSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T03:31:38Z"
    mac: ENC[AES256_GCM,data:A5g3q95uyU5VWzPfO0tHLxWwfRD8Ov54QX2DdRStmmkH35+Hw34aNiZb1zbbCqRJKVrHQt5u2M5ZGksaNItIICy7W2yULjhyfFTL8xt6b46rpRbxL3VHysQaLCqWcbB6zJJBQzclaQGnNmPxVeLpUhlYORkTnMw1RquCqUsAGPc=,iv:VbYBR7gZTXzQRXeSPDMCBKAQMs5hAEygvUiMkN1Rqls=,tag:MbBq5TABcb6vY6Iw2W/Azg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
