---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/observability/kube-prometheus-stack/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 10m
  retryInterval: 1m
  timeout: 5m
