apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-grafana
  namespace: cnpg-system
spec:
  # enableSuperuserAccess: true
  # superuserSecret:
  #   name: grafana-superuser-password
  instances: 1
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      dataChecksums: true
      secret:
        name: grafana-user-password
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  resources:
    requests:
      memory: 300Mi
      cpu:  150m
    limits:
      memory: 300Mi
      cpu: 150m
  storage:
    size: 5Gi
