apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: games
spec:
  type: NodePort
  selector:
    app: palworld
  ports:
    - port: 8211
      name: palworld-port-1
      targetPort: 8211
      nodePort: 31777
      protocol: UDP
    - port: 27015
      name: palworld-port-2
      targetPort: 27015
      nodePort: 32715
      protocol: UDP
    

